WIP global: addition of tests for REST API
inveniosoftware/invenio-accounts-rest pull request #5
Opened 2016-09-09 08:57 UTC by PaulinaLach

* NEW Adds tests for module's REST API. ( #1 )

Signed-off-by: PaulinaLach paulina.malgorzata.lach@cern.ch

2016-09-13 07:49 UTC, jirikuncar commented on tests/conftest.py
> +    return [
`return [create_test_user(**user) for user in users_data]`

2016-09-13 07:49 UTC, jirikuncar commented on tests/conftest.py
> +        r1 = ds.create_role(**roles_data[0])
```python
for role in roles_data:
    ds.create_role(**role)
ds.commit()
```

2016-09-19 12:31 UTC, tiborsimko commented on .travis.yml
> +  - "3.4"
FWIW we decided some time ago to support Python 2.7 and 3.5 only, see https://github.com/inveniosoftware/invenio/issues/3647. Is Python 3.3 or 3.4 needed for B2SHARE? CC @nharraud

2016-11-11 08:40 UTC, nharraud requested changes
Only endpoint changes. Otherwise it looks good for a test-only PR.

2016-11-11 08:40 UTC, nharraud commented on invenio_accounts_rest/views.py
> +    '/roles/<string:role_id>/users/<string:user_id>/assign',
PUT '/roles/<string:role_id>/users/<string:user_id>'
would be more REST (no verb in the URL).

2016-11-11 08:40 UTC, nharraud commented on invenio_accounts_rest/views.py
> +    '/roles/<string:role_id>/users/<string:user_id>/unassign',
DELETE '/roles/string:role_id/users/string:user_id'
would be more REST (no verb in the URL).

2016-11-11 08:40 UTC, nharraud commented on invenio_accounts_rest/views.py
> +    '/users/<string:user_id>/properties',
GET '/users/<string:user_id>'
should be enough IMHO. Or is it conflicting with some other endpoint.

2016-12-14 14:17 UTC, nharraud commented
closing in favor of #7

2016-12-14 14:17 UTC, closed without merging